Gid

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,12 +1,26 @@
 #!/usr/bin/env bash
-#Checking if the number of parameters is less than 4 and display a message
-if [ $# -lt 4 ]; then
-        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-        exit 1
+# Checking for command-line argument
+if [ $# -lt 4 ]
+then
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
-path_2_file=$1
-server_ip=$2
-username=$3
-ssh_key=$4
 
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/
+# Assigning Arguments to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+	echo "FILE TRANSFER FAILED"
+fi
